hens = int(25+30/6)
roosters = int(100-25*3%4)
eggs = int(3+2+1-5+4%2-1/4+6)

print()
print("I will now count my chickens:")
print("Hens",hens)
print("Roosters",roosters)
print("Now I will count the eggs:",eggs)

print()
print("Is it true that 3+2 < 5-7 ?",(3+2)<(5-7))
print("What is 3+2 ?",3+2)
print("What is 5-7 ?",5-7)
print("Oh that's why it's False.")

print()
print("How about some more.")
print("Is it greater?",5 > -2)
print("Is it greater or equal?",5 >= -2)
print("Is it less or equal?",5 <= -2)